###Installing Dependencies

In [1]:
!pip install jsonlines

Collecting jsonlines
  Downloading https://files.pythonhosted.org/packages/4f/9a/ab96291470e305504aa4b7a2e0ec132e930da89eb3ca7a82fbe03167c131/jsonlines-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from jsonlines) (1.11.0)
Installing collected packages: jsonlines
Successfully installed jsonlines-1.2.0

In [0]:
import numpy as np
import pandas as pd
import pickle
import tweepy
from tweepy import OAuthHandler
import json
import jsonlines

###Providing twitter api access tokens

In [0]:
consumer_key = ''
consumer_secret = ''
access_token = ''
access_secret = ''

In [0]:
# Setting authentication using api token keys
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
# Creating api object while calling auth information
api = tweepy.API(auth)

In [0]:
# Name of the twitter account
name = "midasIIITD"
#No. of tweets which can be accessed by api
tweetCount = 200
# Storing the result in results
results = api.user_timeline(id=name, count=tweetCount)

In [0]:
# Creating JSONlines file for accessing data
with jsonlines.open("midas_twitter.jsonl",mode='w') as writer:
    for tweet in results:
        writer.write(tweet._json)

In [0]:
# Function for checking the images
def check_images(entity):
  try:
   media = entity['media']
   return(len(media))
  except KeyError:
   return 'None'

In [0]:
data=[]
# Accessing the JSONline file for further information
with jsonlines.open("midas_twitter.jsonl",mode='r') as reader:
    for item in reader.iter():
        temp=[]
        temp.append(item['text'])
        temp.append(item['created_at'][:16])
        temp.append(item['favorite_count'])
        temp.append(item['retweet_count'])
#         Calling the check_images function for getting the count of images
        image_count = check_images(item['entities'])
        temp.append(image_count)
        data.append(temp)
        
df=pd.DataFrame(data,columns=['Text','Date and time','Number of likes','Nmber of retweets','Number of images'])

In [15]:
# Printing the head of DataFrame
df.head(50)

,Text,Date and time,Number of likes,Nmber of retweets,Number of images
0,RT @Harvard: Professor Jelani Nelson founded A...,Tue Apr 09 05:04,0,30,None
1,RT @emnlp2019: For anyone interested in submit...,Tue Apr 09 05:04,0,11,None
2,RT @multimediaeval: Announcing the 2019 MediaE...,Mon Apr 08 19:38,0,15,None
3,"Many Congratulations to @midasIIITD student, S...",Mon Apr 08 07:08,13,2,None
4,@midasIIITD thanks all students who have appea...,Mon Apr 08 03:27,5,0,None
5,"@himanchalchandr Meanwhile, complete CV/NLP ta...",Sun Apr 07 14:17,0,0,None
6,@sayangdipto123 Submit as per the guideline ag...,Sun Apr 07 14:17,0,0,None
7,We request all students whose interview are sc...,Sun Apr 07 11:43,1,1,None
8,"Other queries: ""none of the Tweeter Apis give ...",Sun Apr 07 06:55,5,2,None
9,"Other queries: ""do we have to make two differe...",Sun Apr 07 06:53,4,1,None
10,"Other queries: ""If using Twitter api, it does ...",Sun Apr 07 05:32,6,1,None
11,Response to some queries asked by students on ...,Sun Apr 07 05:29,7,1,None
12,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,Sat Apr 06 17:11,0,2,None
13,@nupur_baghel @PennDATS Congratulation @nupur_...,Sat Apr 06 16:43,18,3,None
14,We have emailed the task details to all candid...,Fri Apr 05 16:08,11,1,None
15,RT @rfpvjr: Our NAACL paper on polarization in...,Fri Apr 05 04:05,0,16,None
16,RT @kdnuggets: Effective Transfer Learning For...,Fri Apr 05 04:04,0,11,1
17,RT @stanfordnlp: What’s new in @Stanford CS224...,Wed Apr 03 18:31,0,59,None
18,RT @DeepMindAI: Today we're releasing a large-...,Wed Apr 03 17:04,0,870,None
19,RT @ylecun: Congratulations Jitendra Malik !\n...,Wed Apr 03 09:03,0,16,None
20,RT @IIITDelhi: Another chance to take admissio...,Wed Apr 03 07:46,0,4,None
21,Dear @midasIIITD internship candidates who hav...,Tue Apr 02 04:20,8,1,None
22,Looking forward to your paper submission to @I...,Tue Apr 02 02:44,5,1,None
23,RT @ngrams: Reproducibility in multimedia rese...,Tue Apr 02 02:35,0,7,None
24,Online application for https://t.co/DJFDrQsHZP...,Mon Apr 01 06:53,7,2,None
25,RT @ACMMM19: A final reminder of the Reproduci...,Sun Mar 31 10:21,0,10,None
26,RT @isarth23: Thanks for the support and help ...,Fri Mar 29 19:43,0,2,None
27,"Since SemEval-2019 will be held June 6-7, 2019...",Fri Mar 29 17:16,9,1,None
28,+@aggarwal_kartik.\nCongrats! Wish you many mo...,Fri Mar 29 17:04,2,0,None
29,RT @aggarwal_kartik: Our work (@midasIIITD ) a...,Fri Mar 29 17:03,0,1,None
30,"Congratulations! @midasIIITD team, @isarth23 @...",Fri Mar 29 17:02,9,1,None
31,@EEMLcommunity @radamihalcea too many deadline...,Fri Mar 29 05:35,0,0,None
32,RT @stanfordnlp: CS224N Natural Language Proce...,Thu Mar 28 16:55,0,718,None
33,RT @ylecun: Learn PyTorch by running on Google...,Thu Mar 28 16:54,0,155,None
34,Dr. Vineeth N Balasubramanian will present a T...,Wed Mar 27 16:09,4,1,None
35,RT @ylecun: I am extremely honored to be the r...,Wed Mar 27 11:53,0,1545,None
36,Thanks to all shortlisted candidates for submi...,Tue Mar 26 18:12,5,1,None
37,@IEEEBigMM19 @ACMMM19 and 6 days left for work...,Tue Mar 26 05:54,2,0,None
38,RT @IEEEBigMM19: Hurry Up!\n6 Days left for Ab...,Tue Mar 26 05:50,0,3,None
39,Congratulations @midasIIITD students Simra Sha...,Mon Mar 25 13:01,18,1,None
40,The last date for submitting a solution for th...,Sun Mar 24 18:44,8,3,None
41,RT @IIITDelhi: @IIITDelhi invites application ...,Sun Mar 24 18:26,0,4,None
42,One more week is left to submit the workshop p...,Sun Mar 24 11:34,4,0,None
43,RT @IEEEBigMM19: We are honored to have Dr. Ch...,Sun Mar 24 06:23,0,5,None
44,RT @IEEEBigMM19: Distinguished researchers Dr....,Sun Mar 24 06:23,0,3,None
45,@IEEEBigMM19 is also available on Facebook now...,Wed Mar 20 08:19,1,1,None
46,RT @IEEEBigMM19: BigMM 2019 : IEEE BigMM 2019 ...,Wed Mar 20 02:40,0,5,None
47,BigMM 2019 : IEEE BigMM 2019 – Call for Worksh...,Mon Mar 18 02:27,6,3,None
48,"Congratulations @midasIIITD team, Rohan, Prady...",Sun Mar 17 14:22,15,4,None
49,We have emailed the task details to all shortl...,Sat Mar 16 14:06,7,0,None

In [0]:
# Saving the data Frame to csv
df.to_csv('Midas_data.csv')

In [0]:
#  Downloading the csv file
from google.colab import files
files.download('Midas_data.csv')

In [0]:
# Downloading the JSONline file
files.download('midas_twitter.jsonl')